export enum InterviewStage {
  NO_INTERVIEW = 'NO_INTERVIEW',
  PHONE_SCREEN = 'PHONE_SCREEN',
  ONLINE_ASSESSMENT = 'ONLINE_ASSESSMENT',
  BEHAVIORAL = 'BEHAVIORAL',
  TECHNICAL = 'TECHNICAL',
  PANEL = 'PANEL',
  FIRST_ROUND = 'FIRST_ROUND',
  SECOND_ROUND = 'SECOND_ROUND',
  FINAL = 'FINAL',
  DECLINED_INTERVIEW = 'DECLINED_INTERVIEW'
}